In [255]:
import numpy as np

In [257]:
class NeuralNet:
    def __init__(self):
        self.inputs=np.array([[1,1,0,0],[0,1,1,0],[1,1,1,1]])
        self.z=np.array([[1],[0],[1],[0]])
        self.weights_bias1=np.array([[20,20,-10],[-20,-20,30]]) #first layer
        self.weights_bias2=np.array([[20,20,-30]]) #second layer
        self.alpha=0.5
        
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
        
    def sigmoid_der(self, x):
        return (np.exp(-x)/((1+np.exp(-x))**2))
        
    def forward_prop(self):
        self.z1=np.matmul(self.weights_bias1, self.inputs)
        self.a1=self.sigmoid(self.z1)  #activations of first layer
        self.a1=np.vstack((self.a1,np.array([[1,1,1,1]])))
        self.z2=np.matmul(self.weights_bias2, self.a1).T
        self.a2=self.sigmoid(self.z2)  #final output
        
    def cost(self):
        self.forward_prop()
        return ((((self.a2-self.z)**2).sum(0))/4)

    def backprop(self):
        for i in range(10000):
            self.forward_prop()
            c=self.a2-self.z   #derivative of cost wrt final activation
            
            s=self.sigmoid_der(self.z2)    #derivative of final activation wrt the weighted sum obtained from the hidden layer
            
            self.weights_bias2=self.weights_bias2-((self.alpha*np.matmul(self.a1,c*s)).T)  #derivative of weighted sum wrt the weights and biases of hidden layer
            
            delta_a1=np.matmul(c*s, self.weights_bias2[:,0:2])     #derivative of weighted sum wrt the activations of hidden layer
            
            delta_a1=delta_a1.sum(0)/4          #average derivative for each activation over the 4 inputs
            
            s2=self.sigmoid_der(self.z1)        #derivative of the activations of hidden layer wrt weighted sum from input layer
            s2=s2.T
            
            self.weights_bias1=self.weights_bias1-self.alpha*((np.matmul(self.inputs, s2))*(delta_a1)).T   #derivative of the weighted sum from input layer wrt its weights and biases

    def output(self, a, b):
        self.z1=np.matmul(self.weights_bias1, np.array([[a],[b],[1]]))
        self.a1=self.sigmoid(self.z1)
        self.a1=np.vstack((self.a1,np.array([[1]])))
        self.z2=np.matmul(self.weights_bias2, self.a1).T
        self.a2=self.sigmoid(self.z2)
        print(self.a2)
        print(self.weights_bias1)
        print(self.weights_bias2)
        

In [259]:
NN=NeuralNet()

In [261]:
NN.forward_prop()

In [263]:
NN.backprop()

In [264]:
NN.cost()

array([2.06656708e-09])

In [251]:
NN.output(0,1)

[[0.99583733]]
[[ 20.00043261  20.00043261  -9.99870151]
 [-19.99954782 -19.99954782  30.00067812]]
[[ 21.82324984  11.83236993 -28.17666704]]
